name: $PROJ-$ENV-$ENV_UNIT
services:
  mysql:
    image: $PROJ-$APP:$VERSION-$ENV
    entrypoint: "/usr/local/bin/supervisord"
    command: ["-c", "/etc/supervisord.conf"]
    configs:
      - source: mysql-supervisord-conf
        target: /etc/supervisord.conf
      - source: mysql-mysql-conf
        target: /etc/my.cnf
      - source: mysql-initialize-conf
        target: /opt/mysql/mysql${MYSQL_VERSION}/conf/initialize.conf
    volumes:
      - mysql-data:/opt/mysql/mysql${MYSQL_VERSION}/data
      - mysql-log:/opt/mysql/mysql${MYSQL_VERSION}/log
      - ./schema:/opt/mysql/mysql${MYSQL_VERSION}/schema
    networks:
      mysql-subnet:
        ipv4_address: ${MYSQL_NODE_01_IP}
configs:
  mysql-supervisord-conf:
    file: ./config/supervisord.conf
  mysql-initialize-conf:
    file: ./config/initialize.conf
  mysql-mysql-conf:
    file: ./config/my.cnf
volumes:
  mysql-data:
    driver: local
  mysql-log:
    driver: local
networks:
  mysql-subnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${MYSQL_SUBNET_IP_RANGES}
