name: CI Pipeline

on:
  push:
    branches:
      - dev
      - 'release/*'
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
                    startsWith(github.ref, 'refs/heads/release') && 'qa' ||
                    startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ vars.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  build-and-push:
    needs: prepare
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
                    startsWith(github.ref, 'refs/heads/release') && 'qa' ||
                    startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ needs.prepare.outputs.tags }}
          labels: ${{ needs.prepare.outputs.labels }}
          target: ${{ vars.ENV }}
